# Este archivo sirve para crear registros de prueba

#user
User.create(name: "xochitl", email: "xoch@mail.com", password: "xo5")
User.create(name: "adrian", email: "ad@mail.com", password: "ad5")
User.create(name: "victor", email: "vic@mail.com", password: "vi5")
User.create(name: "angela", email: "angi@mail.com", password: "an5")

#deck1 = Deck.create(subject: "Videos")
#deck
Deck.create(subject: "Infantil")
Deck.create(subject: "General")
Deck.create(subject: "Capitales")

#Preguntas Deck1: Infantil
Question.create(deck_id: 1, text: "¿Cómo se llama el más chiquito de los enanos de Blanca Nieves?")
Question.create(deck_id: 1, text: "Nombre de la niña que visitó 'El País de las Maravillas'" )
Question.create(deck_id: 1, text: "¿Qué animal se tragó a Gepetto y a Pinocho?")
Question.create(deck_id: 1, text: "¿Cómo se llama la novia del fortachón 'Popeye el Marino'?")
Question.create(deck_id: 1, text: "¿A quién le crecía la nariz siempre que decía mentiras?")
Question.create(deck_id: 1, text: "¿Cómo se llama el perro de Mickey Mouse?")
Question.create(deck_id: 1, text: "¿Cómo se llama la princesa que tenía cuerpo de pez?")
Question.create(deck_id: 1, text: "¿A quién se le cae la zapatilla en un baile?")
Question.create(deck_id: 1, text: "¿Cómo se llaman las hadas madrinas de la Bella Durmiente?")
Question.create(deck_id: 1, text: "Cómo se traslada Aladín?")

Answer.create(question_id: 1, option: "Tontín", status: true)
Answer.create(question_id: 1, option: "Gruñon", status: false)
Answer.create(question_id: 1, option: "Cariñoso", status: false)
Answer.create(question_id: 2, option: "Alicia", status: true)
Answer.create(question_id: 2, option: "Rapunzel", status: false)
Answer.create(question_id: 2, option: "Mulan", status: false)
Answer.create(question_id: 3, option: "Bella", status: true)
Answer.create(question_id: 3, option: "Mamut", status: false)
Answer.create(question_id: 3, option: "Tiburon", status: false)
Answer.create(question_id: 4, option: "Olivia", status: true)
Answer.create(question_id: 4, option: "Alicia", status: false)
Answer.create(question_id: 4, option: "Vilma", status: false)
Answer.create(question_id: 5, option: "Pinocho", status: true)
Answer.create(question_id: 5, option: "Grillito", status: false)
Answer.create(question_id: 5, option: "otro", status: false)
Answer.create(question_id: 6, option: "Pluto", status: true)
Answer.create(question_id: 6, option: "Perrito", status: false)
Answer.create(question_id: 6, option: "Canelita", status: false)
Answer.create(question_id: 7, option: "Ariel", status: true)
Answer.create(question_id: 7, option: "Bella", status: false)
Answer.create(question_id: 7, option: "Pocahontas", status: false)
Answer.create(question_id: 8, option: "Cenicienta", status: true)
Answer.create(question_id: 8, option: "Bella Durmiente", status: false)
Answer.create(question_id: 8, option: "Luna", status: false)
Answer.create(question_id: 9, option: "Flora, Fauna y Primavera", status: true)
Answer.create(question_id: 9, option: "Flor, Fauna y Primavera", status: false)
Answer.create(question_id: 9, option: "Fauna, Primavera", status: false)
Answer.create(question_id: 10, option: "Alfombra Magica", status: true)
Answer.create(question_id: 10, option: "Tapete", status: false)
Answer.create(question_id: 10, option: "Botella", status: false)

#Preguntas Deck2: General
Question.create(deck_id: 2, text: "¿En qué país se baila y canta la samba?")
Question.create(deck_id: 2, text: "¿Quién anotó con la mano un gol, en el Mundial de México 86?")
Question.create(deck_id: 2, text: "'A lo maduro, a lo maduro, que se voltee....' ¿Cómo se llama la canción?")
Question.create(deck_id: 2, text: "¿Cómo se llama toda colección de animales acuáticos vivos?")
Question.create(deck_id: 2, text: "¿Cuál es el animal más parlanchín?")
Question.create(deck_id: 2, text: "¿Cuántos planetas tiene el Sistema Solar?")
Question.create(deck_id: 2, text: "¿Quién fue el primer hombre que piso la luna?")
Question.create(deck_id: 2, text: "¿Cómo se llama la cría de la ballena?")
Question.create(deck_id: 2, text: "Hermano del héroe Mario")
Question.create(deck_id: 2, text: "¿Para que fueron a visitar al niño Jesús?")

Answer.create(question_id: 11, option: "Brazil", status: true)
Answer.create(question_id: 11, option: "Chile", status: false)
Answer.create(question_id: 11, option: "España", status: false)
Answer.create(question_id: 12, option: "Maradona", status: true)
Answer.create(question_id: 12, option: "Pelé", status: false)
Answer.create(question_id: 12, option: "Ronaldo", status: false)
Answer.create(question_id: 13, option: "Rueda de San Miguel", status: true)
Answer.create(question_id: 13, option: "Doña Blanca", status: false)
Answer.create(question_id: 13, option: "Pim-pom", status: false)
Answer.create(question_id: 14, option: "Acuario", status: true)
Answer.create(question_id: 14, option: "Pecera", status: false)
Answer.create(question_id: 14, option: "Laguna", status: false)
Answer.create(question_id: 15, option: "Perico", status: true)
Answer.create(question_id: 15, option: "Cotorro", status: false)
Answer.create(question_id: 15, option: "Pájaro", status: false)
Answer.create(question_id: 16, option: "Ocho", status: true)
Answer.create(question_id: 16, option: "Diez", status: false)
Answer.create(question_id: 16, option: "Nueve", status: false)
Answer.create(question_id: 17, option: "Neil Amstrong", status: true)
Answer.create(question_id: 17, option: "Alan Bean", status: false)
Answer.create(question_id: 17, option: "William Anders", status: false)
Answer.create(question_id: 18, option: "Ballenato", status: true)
Answer.create(question_id: 18, option: "Ballena", status: false)
Answer.create(question_id: 18, option: "Cria", status: false)
Answer.create(question_id: 19, option: "Luigi", status: true)
Answer.create(question_id: 19, option: "Mario2", status: false)
Answer.create(question_id: 19, option: "Score", status: false)
Answer.create(question_id: 20, option: "Para dar homenaje y regalos", status: true)
Answer.create(question_id: 20, option: "Para bautizarlo", status: false)
Answer.create(question_id: 20, option: "Para hacerle fotos", status: false)

#Preguntas Deck3: Capitales
Question.create(deck_id: 3, text: "Capital de Baja California")
Question.create(deck_id: 3, text: "Capital de Coahuila")
Question.create(deck_id: 3, text: "Capital de Guerrero")
Question.create(deck_id: 3, text: "Capital de México")
Question.create(deck_id: 3, text: "Capital de Nayarit")
Question.create(deck_id: 3, text: "Capital de Quintana Roo")
Question.create(deck_id: 3, text: "Capital de Sinaloa")
Question.create(deck_id: 3, text: "Capital de Tabasco")
Question.create(deck_id: 3, text: "Capital de Yucatan")
Question.create(deck_id: 3, text: "Capital de Baja California Sur")

Answer.create(question_id: 21, option: "Mexicali", status: true)
Answer.create(question_id: 21, option: "Baja California", status: false)
Answer.create(question_id: 21, option: "La Paz", status: false)
Answer.create(question_id: 22, option: "Saltillo", status: true)
Answer.create(question_id: 22, option: "Coahuila", status: false)
Answer.create(question_id: 22, option: "Durango", status: false)
Answer.create(question_id: 23, option: "Chilpancingo", status: true)
Answer.create(question_id: 23, option: "Guerrero", status: false)
Answer.create(question_id: 23, option: "Cd. Guerrero", status: false)
Answer.create(question_id: 24, option: "Toluca", status: true)
Answer.create(question_id: 24, option: "México", status: false)
Answer.create(question_id: 24, option: "Cd. México", status: false)
Answer.create(question_id: 25, option: "Tepic", status: true)
Answer.create(question_id: 25, option: "Nayarit", status: false)
Answer.create(question_id: 25, option: "Colima", status: false)
Answer.create(question_id: 26, option: "Chetumal", status: true)
Answer.create(question_id: 26, option: "Quintana Roo", status: false)
Answer.create(question_id: 26, option: "Mérida", status: false)
Answer.create(question_id: 27, option: "Culiacán", status: true)
Answer.create(question_id: 27, option: "Sinaloa", status: false)
Answer.create(question_id: 27, option: "Sonora", status: false)
Answer.create(question_id: 28, option: "Villahermosa", status: true)
Answer.create(question_id: 28, option: "Tabasco", status: false)
Answer.create(question_id: 28, option: "Chetumal", status: false)
Answer.create(question_id: 29, option: "Mérida", status: true)
Answer.create(question_id: 29, option: "Yucatan", status: false)
Answer.create(question_id: 29, option: "Quintana Roo", status: false)
Answer.create(question_id: 30, option: "La Paz", status: true)
Answer.create(question_id: 30, option: "Baja California", status: false)
Answer.create(question_id: 30, option: "Mexicali", status: false)


#game1 = Game.create(user_id: user.id, deck_id: deck1.id)
#Creando el primer juego prueba
Game.create(user_id: 1, deck_id: 3)

#Statistics
Statistic.create(game_id: 1, question_id: 21, answer_id: 61, score: true)
Statistic.create(game_id: 1, question_id: 22, answer_id: 64, score: true)
Statistic.create(game_id: 1, question_id: 23, answer_id: 67, score: true)
Statistic.create(game_id: 1, question_id: 24, answer_id: 70, score: true)
Statistic.create(game_id: 1, question_id: 25, answer_id: 73, score: true)
Statistic.create(game_id: 1, question_id: 26, answer_id: 76, score: true)
Statistic.create(game_id: 1, question_id: 27, answer_id: 79, score: true)
Statistic.create(game_id: 1, question_id: 28, answer_id: 82, score: true)
Statistic.create(game_id: 1, question_id: 29, answer_id: 86, score: false) #85
Statistic.create(game_id: 1, question_id: 30, answer_id: 89, score: false) #88



